/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PartitionSpec } from './PartitionSpec';
import {
    PartitionSpecFromJSON,
    PartitionSpecFromJSONTyped,
    PartitionSpecToJSON,
} from './PartitionSpec';

/**
 * 
 * @export
 * @interface AddPartitionSpecUpdate
 */
export interface AddPartitionSpecUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddPartitionSpecUpdate
     */
    action: AddPartitionSpecUpdateActionEnum;
    /**
     * 
     * @type {PartitionSpec}
     * @memberof AddPartitionSpecUpdate
     */
    spec: PartitionSpec;
}


/**
 * @export
 */
export const AddPartitionSpecUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type AddPartitionSpecUpdateActionEnum = typeof AddPartitionSpecUpdateActionEnum[keyof typeof AddPartitionSpecUpdateActionEnum];


/**
 * Check if a given object implements the AddPartitionSpecUpdate interface.
 */
export function instanceOfAddPartitionSpecUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function AddPartitionSpecUpdateFromJSON(json: any): AddPartitionSpecUpdate {
    return AddPartitionSpecUpdateFromJSONTyped(json, false);
}

export function AddPartitionSpecUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPartitionSpecUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'spec': PartitionSpecFromJSON(json['spec']),
    };
}

export function AddPartitionSpecUpdateToJSON(value?: AddPartitionSpecUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'spec': PartitionSpecToJSON(value.spec),
    };
}

