/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';

/**
 * 
 * @export
 * @interface AddSortOrderUpdate
 */
export interface AddSortOrderUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddSortOrderUpdate
     */
    action: AddSortOrderUpdateActionEnum;
    /**
     * 
     * @type {SortOrder}
     * @memberof AddSortOrderUpdate
     */
    sortOrder: SortOrder;
}


/**
 * @export
 */
export const AddSortOrderUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type AddSortOrderUpdateActionEnum = typeof AddSortOrderUpdateActionEnum[keyof typeof AddSortOrderUpdateActionEnum];


/**
 * Check if a given object implements the AddSortOrderUpdate interface.
 */
export function instanceOfAddSortOrderUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "sortOrder" in value;

    return isInstance;
}

export function AddSortOrderUpdateFromJSON(json: any): AddSortOrderUpdate {
    return AddSortOrderUpdateFromJSONTyped(json, false);
}

export function AddSortOrderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSortOrderUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'sortOrder': SortOrderFromJSON(json['sort-order']),
    };
}

export function AddSortOrderUpdateToJSON(value?: AddSortOrderUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'sort-order': SortOrderToJSON(value.sortOrder),
    };
}

