/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Snapshot } from './Snapshot';
import {
    SnapshotFromJSON,
    SnapshotFromJSONTyped,
    SnapshotToJSON,
} from './Snapshot';

/**
 * 
 * @export
 * @interface AddSnapshotUpdateAllOf
 */
export interface AddSnapshotUpdateAllOf {
    /**
     * 
     * @type {Snapshot}
     * @memberof AddSnapshotUpdateAllOf
     */
    snapshot: Snapshot;
}

/**
 * Check if a given object implements the AddSnapshotUpdateAllOf interface.
 */
export function instanceOfAddSnapshotUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "snapshot" in value;

    return isInstance;
}

export function AddSnapshotUpdateAllOfFromJSON(json: any): AddSnapshotUpdateAllOf {
    return AddSnapshotUpdateAllOfFromJSONTyped(json, false);
}

export function AddSnapshotUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSnapshotUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'snapshot': SnapshotFromJSON(json['snapshot']),
    };
}

export function AddSnapshotUpdateAllOfToJSON(value?: AddSnapshotUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'snapshot': SnapshotToJSON(value.snapshot),
    };
}

