/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Snapshot } from './Snapshot';
import {
    SnapshotFromJSON,
    SnapshotFromJSONTyped,
    SnapshotToJSON,
} from './Snapshot';

/**
 * 
 * @export
 * @interface AddSnapshotUpdate
 */
export interface AddSnapshotUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddSnapshotUpdate
     */
    action: AddSnapshotUpdateActionEnum;
    /**
     * 
     * @type {Snapshot}
     * @memberof AddSnapshotUpdate
     */
    snapshot: Snapshot;
}


/**
 * @export
 */
export const AddSnapshotUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type AddSnapshotUpdateActionEnum = typeof AddSnapshotUpdateActionEnum[keyof typeof AddSnapshotUpdateActionEnum];


/**
 * Check if a given object implements the AddSnapshotUpdate interface.
 */
export function instanceOfAddSnapshotUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "snapshot" in value;

    return isInstance;
}

export function AddSnapshotUpdateFromJSON(json: any): AddSnapshotUpdate {
    return AddSnapshotUpdateFromJSONTyped(json, false);
}

export function AddSnapshotUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSnapshotUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'snapshot': SnapshotFromJSON(json['snapshot']),
    };
}

export function AddSnapshotUpdateToJSON(value?: AddSnapshotUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'snapshot': SnapshotToJSON(value.snapshot),
    };
}

