/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetricResult } from './MetricResult';
import {
    MetricResultFromJSON,
    MetricResultFromJSONTyped,
    MetricResultToJSON,
} from './MetricResult';

/**
 * 
 * @export
 * @interface CommitReport
 */
export interface CommitReport {
    /**
     * 
     * @type {string}
     * @memberof CommitReport
     */
    tableName: string;
    /**
     * 
     * @type {number}
     * @memberof CommitReport
     */
    snapshotId: number;
    /**
     * 
     * @type {number}
     * @memberof CommitReport
     */
    sequenceNumber: number;
    /**
     * 
     * @type {string}
     * @memberof CommitReport
     */
    operation: string;
    /**
     * 
     * @type {{ [key: string]: MetricResult; }}
     * @memberof CommitReport
     */
    metrics: { [key: string]: MetricResult; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommitReport
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CommitReport interface.
 */
export function instanceOfCommitReport(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tableName" in value;
    isInstance = isInstance && "snapshotId" in value;
    isInstance = isInstance && "sequenceNumber" in value;
    isInstance = isInstance && "operation" in value;
    isInstance = isInstance && "metrics" in value;

    return isInstance;
}

export function CommitReportFromJSON(json: any): CommitReport {
    return CommitReportFromJSONTyped(json, false);
}

export function CommitReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tableName': json['table-name'],
        'snapshotId': json['snapshot-id'],
        'sequenceNumber': json['sequence-number'],
        'operation': json['operation'],
        'metrics': (mapValues(json['metrics'], MetricResultFromJSON)),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function CommitReportToJSON(value?: CommitReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'table-name': value.tableName,
        'snapshot-id': value.snapshotId,
        'sequence-number': value.sequenceNumber,
        'operation': value.operation,
        'metrics': (mapValues(value.metrics, MetricResultToJSON)),
        'metadata': value.metadata,
    };
}

