/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorModel } from './ErrorModel';
import {
    ErrorModelFromJSON,
    ErrorModelFromJSONTyped,
    ErrorModelToJSON,
} from './ErrorModel';

/**
 * 
 * @export
 * @interface IcebergErrorResponse
 */
export interface IcebergErrorResponse {
    /**
     * 
     * @type {ErrorModel}
     * @memberof IcebergErrorResponse
     */
    error?: ErrorModel;
}

/**
 * Check if a given object implements the IcebergErrorResponse interface.
 */
export function instanceOfIcebergErrorResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IcebergErrorResponseFromJSON(json: any): IcebergErrorResponse {
    return IcebergErrorResponseFromJSONTyped(json, false);
}

export function IcebergErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IcebergErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorModelFromJSON(json['error']),
    };
}

export function IcebergErrorResponseToJSON(value?: IcebergErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorModelToJSON(value.error),
    };
}

