/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNamespacesResponse
 */
export interface ListNamespacesResponse {
    /**
     * 
     * @type {Set<Array<string>>}
     * @memberof ListNamespacesResponse
     */
    namespaces?: Set<Array<string>>;
}

/**
 * Check if a given object implements the ListNamespacesResponse interface.
 */
export function instanceOfListNamespacesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListNamespacesResponseFromJSON(json: any): ListNamespacesResponse {
    return ListNamespacesResponseFromJSONTyped(json, false);
}

export function ListNamespacesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNamespacesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'namespaces': !exists(json, 'namespaces') ? undefined : json['namespaces'],
    };
}

export function ListNamespacesResponseToJSON(value?: ListNamespacesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'namespaces': value.namespaces === undefined ? undefined : Array.from(value.namespaces as Set<any>),
    };
}

