/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataLogInner
 */
export interface MetadataLogInner {
    /**
     * 
     * @type {string}
     * @memberof MetadataLogInner
     */
    metadataFile: string;
    /**
     * 
     * @type {number}
     * @memberof MetadataLogInner
     */
    timestampMs: number;
}

/**
 * Check if a given object implements the MetadataLogInner interface.
 */
export function instanceOfMetadataLogInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadataFile" in value;
    isInstance = isInstance && "timestampMs" in value;

    return isInstance;
}

export function MetadataLogInnerFromJSON(json: any): MetadataLogInner {
    return MetadataLogInnerFromJSONTyped(json, false);
}

export function MetadataLogInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataLogInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadataFile': json['metadata-file'],
        'timestampMs': json['timestamp-ms'],
    };
}

export function MetadataLogInnerToJSON(value?: MetadataLogInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata-file': value.metadataFile,
        'timestamp-ms': value.timestampMs,
    };
}

