/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemovePropertiesUpdateAllOf
 */
export interface RemovePropertiesUpdateAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemovePropertiesUpdateAllOf
     */
    removals: Array<string>;
}

/**
 * Check if a given object implements the RemovePropertiesUpdateAllOf interface.
 */
export function instanceOfRemovePropertiesUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "removals" in value;

    return isInstance;
}

export function RemovePropertiesUpdateAllOfFromJSON(json: any): RemovePropertiesUpdateAllOf {
    return RemovePropertiesUpdateAllOfFromJSONTyped(json, false);
}

export function RemovePropertiesUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePropertiesUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'removals': json['removals'],
    };
}

export function RemovePropertiesUpdateAllOfToJSON(value?: RemovePropertiesUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'removals': value.removals,
    };
}

