/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetCurrentSchemaUpdate
 */
export interface SetCurrentSchemaUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetCurrentSchemaUpdate
     */
    action: SetCurrentSchemaUpdateActionEnum;
    /**
     * Schema ID to set as current, or -1 to set last added schema
     * @type {number}
     * @memberof SetCurrentSchemaUpdate
     */
    schemaId: number;
}


/**
 * @export
 */
export const SetCurrentSchemaUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type SetCurrentSchemaUpdateActionEnum = typeof SetCurrentSchemaUpdateActionEnum[keyof typeof SetCurrentSchemaUpdateActionEnum];


/**
 * Check if a given object implements the SetCurrentSchemaUpdate interface.
 */
export function instanceOfSetCurrentSchemaUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "schemaId" in value;

    return isInstance;
}

export function SetCurrentSchemaUpdateFromJSON(json: any): SetCurrentSchemaUpdate {
    return SetCurrentSchemaUpdateFromJSONTyped(json, false);
}

export function SetCurrentSchemaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCurrentSchemaUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'schemaId': json['schema-id'],
    };
}

export function SetCurrentSchemaUpdateToJSON(value?: SetCurrentSchemaUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'schema-id': value.schemaId,
    };
}

