/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetCurrentSchemaUpdateAllOf
 */
export interface SetCurrentSchemaUpdateAllOf {
    /**
     * Schema ID to set as current, or -1 to set last added schema
     * @type {number}
     * @memberof SetCurrentSchemaUpdateAllOf
     */
    schemaId: number;
}

/**
 * Check if a given object implements the SetCurrentSchemaUpdateAllOf interface.
 */
export function instanceOfSetCurrentSchemaUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "schemaId" in value;

    return isInstance;
}

export function SetCurrentSchemaUpdateAllOfFromJSON(json: any): SetCurrentSchemaUpdateAllOf {
    return SetCurrentSchemaUpdateAllOfFromJSONTyped(json, false);
}

export function SetCurrentSchemaUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCurrentSchemaUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schemaId': json['schema-id'],
    };
}

export function SetCurrentSchemaUpdateAllOfToJSON(value?: SetCurrentSchemaUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema-id': value.schemaId,
    };
}

