/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetDefaultSpecUpdateAllOf
 */
export interface SetDefaultSpecUpdateAllOf {
    /**
     * Partition spec ID to set as the default, or -1 to set last added spec
     * @type {number}
     * @memberof SetDefaultSpecUpdateAllOf
     */
    specId: number;
}

/**
 * Check if a given object implements the SetDefaultSpecUpdateAllOf interface.
 */
export function instanceOfSetDefaultSpecUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "specId" in value;

    return isInstance;
}

export function SetDefaultSpecUpdateAllOfFromJSON(json: any): SetDefaultSpecUpdateAllOf {
    return SetDefaultSpecUpdateAllOfFromJSONTyped(json, false);
}

export function SetDefaultSpecUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetDefaultSpecUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'specId': json['spec-id'],
    };
}

export function SetDefaultSpecUpdateAllOfToJSON(value?: SetDefaultSpecUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spec-id': value.specId,
    };
}

