/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetLocationUpdate
 */
export interface SetLocationUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetLocationUpdate
     */
    action: SetLocationUpdateActionEnum;
    /**
     * 
     * @type {string}
     * @memberof SetLocationUpdate
     */
    location: string;
}


/**
 * @export
 */
export const SetLocationUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type SetLocationUpdateActionEnum = typeof SetLocationUpdateActionEnum[keyof typeof SetLocationUpdateActionEnum];


/**
 * Check if a given object implements the SetLocationUpdate interface.
 */
export function instanceOfSetLocationUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function SetLocationUpdateFromJSON(json: any): SetLocationUpdate {
    return SetLocationUpdateFromJSONTyped(json, false);
}

export function SetLocationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetLocationUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'location': json['location'],
    };
}

export function SetLocationUpdateToJSON(value?: SetLocationUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'location': value.location,
    };
}

