/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetLocationUpdateAllOf
 */
export interface SetLocationUpdateAllOf {
    /**
     * 
     * @type {string}
     * @memberof SetLocationUpdateAllOf
     */
    location: string;
}

/**
 * Check if a given object implements the SetLocationUpdateAllOf interface.
 */
export function instanceOfSetLocationUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function SetLocationUpdateAllOfFromJSON(json: any): SetLocationUpdateAllOf {
    return SetLocationUpdateAllOfFromJSONTyped(json, false);
}

export function SetLocationUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetLocationUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': json['location'],
    };
}

export function SetLocationUpdateAllOfToJSON(value?: SetLocationUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': value.location,
    };
}

