/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPropertiesUpdate
 */
export interface SetPropertiesUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetPropertiesUpdate
     */
    action: SetPropertiesUpdateActionEnum;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SetPropertiesUpdate
     */
    updates: { [key: string]: string; };
}


/**
 * @export
 */
export const SetPropertiesUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type SetPropertiesUpdateActionEnum = typeof SetPropertiesUpdateActionEnum[keyof typeof SetPropertiesUpdateActionEnum];


/**
 * Check if a given object implements the SetPropertiesUpdate interface.
 */
export function instanceOfSetPropertiesUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "updates" in value;

    return isInstance;
}

export function SetPropertiesUpdateFromJSON(json: any): SetPropertiesUpdate {
    return SetPropertiesUpdateFromJSONTyped(json, false);
}

export function SetPropertiesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPropertiesUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'updates': json['updates'],
    };
}

export function SetPropertiesUpdateToJSON(value?: SetPropertiesUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'updates': value.updates,
    };
}

