/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPropertiesUpdateAllOf
 */
export interface SetPropertiesUpdateAllOf {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SetPropertiesUpdateAllOf
     */
    updates: { [key: string]: string; };
}

/**
 * Check if a given object implements the SetPropertiesUpdateAllOf interface.
 */
export function instanceOfSetPropertiesUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "updates" in value;

    return isInstance;
}

export function SetPropertiesUpdateAllOfFromJSON(json: any): SetPropertiesUpdateAllOf {
    return SetPropertiesUpdateAllOfFromJSONTyped(json, false);
}

export function SetPropertiesUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPropertiesUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updates': json['updates'],
    };
}

export function SetPropertiesUpdateAllOfToJSON(value?: SetPropertiesUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updates': value.updates,
    };
}

