/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetSnapshotRefUpdate
 */
export interface SetSnapshotRefUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetSnapshotRefUpdate
     */
    action: SetSnapshotRefUpdateActionEnum;
    /**
     * 
     * @type {string}
     * @memberof SetSnapshotRefUpdate
     */
    type: SetSnapshotRefUpdateTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SetSnapshotRefUpdate
     */
    snapshotId: number;
    /**
     * 
     * @type {number}
     * @memberof SetSnapshotRefUpdate
     */
    maxRefAgeMs?: number;
    /**
     * 
     * @type {number}
     * @memberof SetSnapshotRefUpdate
     */
    maxSnapshotAgeMs?: number;
    /**
     * 
     * @type {number}
     * @memberof SetSnapshotRefUpdate
     */
    minSnapshotsToKeep?: number;
    /**
     * 
     * @type {string}
     * @memberof SetSnapshotRefUpdate
     */
    refName: string;
}


/**
 * @export
 */
export const SetSnapshotRefUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type SetSnapshotRefUpdateActionEnum = typeof SetSnapshotRefUpdateActionEnum[keyof typeof SetSnapshotRefUpdateActionEnum];

/**
 * @export
 */
export const SetSnapshotRefUpdateTypeEnum = {
    Tag: 'tag',
    Branch: 'branch'
} as const;
export type SetSnapshotRefUpdateTypeEnum = typeof SetSnapshotRefUpdateTypeEnum[keyof typeof SetSnapshotRefUpdateTypeEnum];


/**
 * Check if a given object implements the SetSnapshotRefUpdate interface.
 */
export function instanceOfSetSnapshotRefUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "snapshotId" in value;
    isInstance = isInstance && "refName" in value;

    return isInstance;
}

export function SetSnapshotRefUpdateFromJSON(json: any): SetSnapshotRefUpdate {
    return SetSnapshotRefUpdateFromJSONTyped(json, false);
}

export function SetSnapshotRefUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetSnapshotRefUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'type': json['type'],
        'snapshotId': json['snapshot-id'],
        'maxRefAgeMs': !exists(json, 'max-ref-age-ms') ? undefined : json['max-ref-age-ms'],
        'maxSnapshotAgeMs': !exists(json, 'max-snapshot-age-ms') ? undefined : json['max-snapshot-age-ms'],
        'minSnapshotsToKeep': !exists(json, 'min-snapshots-to-keep') ? undefined : json['min-snapshots-to-keep'],
        'refName': json['ref-name'],
    };
}

export function SetSnapshotRefUpdateToJSON(value?: SetSnapshotRefUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'type': value.type,
        'snapshot-id': value.snapshotId,
        'max-ref-age-ms': value.maxRefAgeMs,
        'max-snapshot-age-ms': value.maxSnapshotAgeMs,
        'min-snapshots-to-keep': value.minSnapshotsToKeep,
        'ref-name': value.refName,
    };
}

