/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetSnapshotRefUpdateAllOf
 */
export interface SetSnapshotRefUpdateAllOf {
    /**
     * 
     * @type {string}
     * @memberof SetSnapshotRefUpdateAllOf
     */
    refName: string;
}

/**
 * Check if a given object implements the SetSnapshotRefUpdateAllOf interface.
 */
export function instanceOfSetSnapshotRefUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "refName" in value;

    return isInstance;
}

export function SetSnapshotRefUpdateAllOfFromJSON(json: any): SetSnapshotRefUpdateAllOf {
    return SetSnapshotRefUpdateAllOfFromJSONTyped(json, false);
}

export function SetSnapshotRefUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetSnapshotRefUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refName': json['ref-name'],
    };
}

export function SetSnapshotRefUpdateAllOfToJSON(value?: SetSnapshotRefUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ref-name': value.refName,
    };
}

