/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotSummary
 */
export interface SnapshotSummary {
    /**
     * 
     * @type {string}
     * @memberof SnapshotSummary
     */
    operation: SnapshotSummaryOperationEnum;
    /**
     * 
     * @type {string}
     * @memberof SnapshotSummary
     */
    additionalProperties?: string;
}


/**
 * @export
 */
export const SnapshotSummaryOperationEnum = {
    Append: 'append',
    Replace: 'replace',
    Overwrite: 'overwrite',
    Delete: 'delete'
} as const;
export type SnapshotSummaryOperationEnum = typeof SnapshotSummaryOperationEnum[keyof typeof SnapshotSummaryOperationEnum];


/**
 * Check if a given object implements the SnapshotSummary interface.
 */
export function instanceOfSnapshotSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "operation" in value;

    return isInstance;
}

export function SnapshotSummaryFromJSON(json: any): SnapshotSummary {
    return SnapshotSummaryFromJSONTyped(json, false);
}

export function SnapshotSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'operation': json['operation'],
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : json['additionalProperties'],
    };
}

export function SnapshotSummaryToJSON(value?: SnapshotSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'operation': value.operation,
        'additionalProperties': value.additionalProperties,
    };
}

