/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimerResult
 */
export interface TimerResult {
    /**
     * 
     * @type {string}
     * @memberof TimerResult
     */
    timeUnit: string;
    /**
     * 
     * @type {number}
     * @memberof TimerResult
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof TimerResult
     */
    totalDuration: number;
}

/**
 * Check if a given object implements the TimerResult interface.
 */
export function instanceOfTimerResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "timeUnit" in value;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "totalDuration" in value;

    return isInstance;
}

export function TimerResultFromJSON(json: any): TimerResult {
    return TimerResultFromJSONTyped(json, false);
}

export function TimerResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimerResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeUnit': json['time-unit'],
        'count': json['count'],
        'totalDuration': json['total-duration'],
    };
}

export function TimerResultToJSON(value?: TimerResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time-unit': value.timeUnit,
        'count': value.count,
        'total-duration': value.totalDuration,
    };
}

