/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ListType,
    instanceOfListType,
    ListTypeFromJSON,
    ListTypeFromJSONTyped,
    ListTypeToJSON,
} from './ListType';
import {
    MapType,
    instanceOfMapType,
    MapTypeFromJSON,
    MapTypeFromJSONTyped,
    MapTypeToJSON,
} from './MapType';
import {
    StructType,
    instanceOfStructType,
    StructTypeFromJSON,
    StructTypeFromJSONTyped,
    StructTypeToJSON,
} from './StructType';

/**
 * @type Type
 * 
 * @export
 */
export type Type = ListType | MapType | StructType | string;

export function TypeFromJSON(json: any): Type {
    return TypeFromJSONTyped(json, false);
}

export function TypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Type {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ListTypeFromJSONTyped(json, true), ...MapTypeFromJSONTyped(json, true), ...StructTypeFromJSONTyped(json, true), ...(JSON.stringify(json) as unknown as object) };
}

export function TypeToJSON(value?: Type | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfListType(value as object)) {
        return ListTypeToJSON(value as ListType);
    }
    if (instanceOfMapType(value as object)) {
        return MapTypeToJSON(value as MapType);
    }
    if (instanceOfStructType(value as object)) {
        return StructTypeToJSON(value as StructType);
    }
    if (value instanceof String) {
        return JSON.parse(value as string);
    }

    return {};
}

