/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpgradeFormatVersionUpdate
 */
export interface UpgradeFormatVersionUpdate {
    /**
     * 
     * @type {string}
     * @memberof UpgradeFormatVersionUpdate
     */
    action: UpgradeFormatVersionUpdateActionEnum;
    /**
     * 
     * @type {number}
     * @memberof UpgradeFormatVersionUpdate
     */
    formatVersion: number;
}


/**
 * @export
 */
export const UpgradeFormatVersionUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version',
    AddSchema: 'add-schema',
    SetCurrentSchema: 'set-current-schema',
    AddSpec: 'add-spec',
    SetDefaultSpec: 'set-default-spec',
    AddSortOrder: 'add-sort-order',
    SetDefaultSortOrder: 'set-default-sort-order',
    AddSnapshot: 'add-snapshot',
    SetSnapshotRef: 'set-snapshot-ref',
    RemoveSnapshots: 'remove-snapshots',
    RemoveSnapshotRef: 'remove-snapshot-ref',
    SetLocation: 'set-location',
    SetProperties: 'set-properties',
    RemoveProperties: 'remove-properties'
} as const;
export type UpgradeFormatVersionUpdateActionEnum = typeof UpgradeFormatVersionUpdateActionEnum[keyof typeof UpgradeFormatVersionUpdateActionEnum];


/**
 * Check if a given object implements the UpgradeFormatVersionUpdate interface.
 */
export function instanceOfUpgradeFormatVersionUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "formatVersion" in value;

    return isInstance;
}

export function UpgradeFormatVersionUpdateFromJSON(json: any): UpgradeFormatVersionUpdate {
    return UpgradeFormatVersionUpdateFromJSONTyped(json, false);
}

export function UpgradeFormatVersionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeFormatVersionUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'formatVersion': json['format-version'],
    };
}

export function UpgradeFormatVersionUpdateToJSON(value?: UpgradeFormatVersionUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'format-version': value.formatVersion,
    };
}

