/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpgradeFormatVersionUpdateAllOf
 */
export interface UpgradeFormatVersionUpdateAllOf {
    /**
     * 
     * @type {number}
     * @memberof UpgradeFormatVersionUpdateAllOf
     */
    formatVersion: number;
}

/**
 * Check if a given object implements the UpgradeFormatVersionUpdateAllOf interface.
 */
export function instanceOfUpgradeFormatVersionUpdateAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "formatVersion" in value;

    return isInstance;
}

export function UpgradeFormatVersionUpdateAllOfFromJSON(json: any): UpgradeFormatVersionUpdateAllOf {
    return UpgradeFormatVersionUpdateAllOfFromJSONTyped(json, false);
}

export function UpgradeFormatVersionUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeFormatVersionUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formatVersion': json['format-version'],
    };
}

export function UpgradeFormatVersionUpdateAllOfToJSON(value?: UpgradeFormatVersionUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'format-version': value.formatVersion,
    };
}

