/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Snapshot } from '../models/Snapshot';
import { HttpFile } from '../http/http';

export class AddSnapshotUpdate {
    'action': AddSnapshotUpdateActionEnum;
    'snapshot': Snapshot;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AddSnapshotUpdateActionEnum",
            "format": ""
        },
        {
            "name": "snapshot",
            "baseName": "snapshot",
            "type": "Snapshot",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddSnapshotUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AddSnapshotUpdateActionEnum = "upgrade-format-version" | "add-schema" | "set-current-schema" | "add-spec" | "set-default-spec" | "add-sort-order" | "set-default-sort-order" | "add-snapshot" | "set-snapshot-ref" | "remove-snapshots" | "remove-snapshot-ref" | "set-location" | "set-properties" | "remove-properties" ;

