/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Server-provided configuration for the catalog.
*/
export class CatalogConfig {
    /**
    * Properties that should be used to override client configuration; applied after defaults and client configuration.
    */
    'overrides': any;
    /**
    * Properties that should be used as default configuration; applied before client configuration.
    */
    'defaults': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "overrides",
            "baseName": "overrides",
            "type": "any",
            "format": ""
        },
        {
            "name": "defaults",
            "baseName": "defaults",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CatalogConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

