/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PartitionSpec } from '../models/PartitionSpec';
import { Schema } from '../models/Schema';
import { SortOrder } from '../models/SortOrder';
import { HttpFile } from '../http/http';

export class CreateTableRequest {
    'name': string;
    'location'?: string;
    'schema': Schema;
    'partitionSpec'?: PartitionSpec;
    'writeOrder'?: SortOrder;
    'stageCreate'?: boolean;
    'properties'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "Schema",
            "format": ""
        },
        {
            "name": "partitionSpec",
            "baseName": "partition-spec",
            "type": "PartitionSpec",
            "format": ""
        },
        {
            "name": "writeOrder",
            "baseName": "write-order",
            "type": "SortOrder",
            "format": ""
        },
        {
            "name": "stageCreate",
            "baseName": "stage-create",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateTableRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

