/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AndOrExpression } from '../models/AndOrExpression';
import { LiteralExpression } from '../models/LiteralExpression';
import { NotExpression } from '../models/NotExpression';
import { SetExpression } from '../models/SetExpression';
import { Term } from '../models/Term';
import { UnaryExpression } from '../models/UnaryExpression';
import { HttpFile } from '../http/http';

export class Expression {
    'type': string;
    'left': Expression;
    'right': Expression;
    'child': Expression;
    'term': Term;
    'values': Array<any>;
    'value': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "left",
            "baseName": "left",
            "type": "Expression",
            "format": ""
        },
        {
            "name": "right",
            "baseName": "right",
            "type": "Expression",
            "format": ""
        },
        {
            "name": "child",
            "baseName": "child",
            "type": "Expression",
            "format": ""
        },
        {
            "name": "term",
            "baseName": "term",
            "type": "Term",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Expression.attributeTypeMap;
    }

    public constructor() {
    }
}

