/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetToken400Response {
    'error': GetToken400ResponseModelErrorEnum;
    'errorDescription'?: string;
    'errorUri'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "GetToken400ResponseModelErrorEnum",
            "format": ""
        },
        {
            "name": "errorDescription",
            "baseName": "error_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorUri",
            "baseName": "error_uri",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetToken400Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetToken400ResponseModelErrorEnum = "invalid_request" | "invalid_client" | "invalid_grant" | "unauthorized_client" | "unsupported_grant_type" | "invalid_scope" ;

