/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TokenType } from '../models/TokenType';
import { HttpFile } from '../http/http';

export class GetToken200Response {
    /**
    * The access token, for client credentials or token exchange
    */
    'accessToken': string;
    /**
    * Access token type for client credentials or token exchange  See https://datatracker.ietf.org/doc/html/rfc6749#section-7.1
    */
    'tokenType': GetToken200ResponseTokenTypeEnum;
    /**
    * Lifetime of the access token in seconds for client credentials or token exchange
    */
    'expiresIn'?: number;
    'issuedTokenType'?: TokenType;
    /**
    * Refresh token for client credentials or token exchange
    */
    'refreshToken'?: string;
    /**
    * Authorization scope for client credentials or token exchange
    */
    'scope'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenType",
            "baseName": "token_type",
            "type": "GetToken200ResponseTokenTypeEnum",
            "format": ""
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number",
            "format": ""
        },
        {
            "name": "issuedTokenType",
            "baseName": "issued_token_type",
            "type": "TokenType",
            "format": ""
        },
        {
            "name": "refreshToken",
            "baseName": "refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetToken200Response.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GetToken200ResponseTokenTypeEnum = "bearer" | "mac" | "N_A" ;

