/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Type } from '../models/Type';
import { HttpFile } from '../http/http';

export class ListType {
    'type': ListTypeTypeEnum;
    'elementId': number;
    'element': Type;
    'elementRequired': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ListTypeTypeEnum",
            "format": ""
        },
        {
            "name": "elementId",
            "baseName": "element-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "element",
            "baseName": "element",
            "type": "Type",
            "format": ""
        },
        {
            "name": "elementRequired",
            "baseName": "element-required",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListType.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ListTypeTypeEnum = "list" ;

