/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Expression } from '../models/Expression';
import { MetricResult } from '../models/MetricResult';
import { ScanReport } from '../models/ScanReport';
import { HttpFile } from '../http/http';

export class ReportMetricsRequest {
    'reportType': string;
    'tableName': string;
    'snapshotId': number;
    'filter': Expression;
    'schemaId': number;
    'projectedFieldIds': Array<number>;
    'projectedFieldNames': Array<string>;
    'metrics': { [key: string]: MetricResult; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reportType",
            "baseName": "report-type",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableName",
            "baseName": "table-name",
            "type": "string",
            "format": ""
        },
        {
            "name": "snapshotId",
            "baseName": "snapshot-id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Expression",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "projectedFieldIds",
            "baseName": "projected-field-ids",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "projectedFieldNames",
            "baseName": "projected-field-names",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "{ [key: string]: MetricResult; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReportMetricsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

