/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StructField } from '../models/StructField';
import { HttpFile } from '../http/http';

export class Schema {
    'type': SchemaTypeEnum;
    'fields': Array<StructField>;
    'schemaId'?: number;
    'identifierFieldIds'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SchemaTypeEnum",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<StructField>",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "identifierFieldIds",
            "baseName": "identifier-field-ids",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Schema.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SchemaTypeEnum = "struct" ;

