/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SetSnapshotRefUpdate {
    'action': SetSnapshotRefUpdateActionEnum;
    'type': SetSnapshotRefUpdateTypeEnum;
    'snapshotId': number;
    'maxRefAgeMs'?: number;
    'maxSnapshotAgeMs'?: number;
    'minSnapshotsToKeep'?: number;
    'refName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "SetSnapshotRefUpdateActionEnum",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SetSnapshotRefUpdateTypeEnum",
            "format": ""
        },
        {
            "name": "snapshotId",
            "baseName": "snapshot-id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRefAgeMs",
            "baseName": "max-ref-age-ms",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxSnapshotAgeMs",
            "baseName": "max-snapshot-age-ms",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minSnapshotsToKeep",
            "baseName": "min-snapshots-to-keep",
            "type": "number",
            "format": ""
        },
        {
            "name": "refName",
            "baseName": "ref-name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SetSnapshotRefUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SetSnapshotRefUpdateActionEnum = "upgrade-format-version" | "add-schema" | "set-current-schema" | "add-spec" | "set-default-spec" | "add-sort-order" | "set-default-sort-order" | "add-snapshot" | "set-snapshot-ref" | "remove-snapshots" | "remove-snapshot-ref" | "set-location" | "set-properties" | "remove-properties" ;
export type SetSnapshotRefUpdateTypeEnum = "tag" | "branch" ;

