/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnapshotSummary } from '../models/SnapshotSummary';
import { HttpFile } from '../http/http';

export class Snapshot {
    'snapshotId': number;
    'parentSnapshotId'?: number;
    'sequenceNumber'?: number;
    'timestampMs': number;
    /**
    * Location of the snapshot's manifest list file
    */
    'manifestList': string;
    'summary': SnapshotSummary;
    'schemaId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "snapshotId",
            "baseName": "snapshot-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "parentSnapshotId",
            "baseName": "parent-snapshot-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "sequenceNumber",
            "baseName": "sequence-number",
            "type": "number",
            "format": ""
        },
        {
            "name": "timestampMs",
            "baseName": "timestamp-ms",
            "type": "number",
            "format": ""
        },
        {
            "name": "manifestList",
            "baseName": "manifest-list",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "SnapshotSummary",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema-id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Snapshot.attributeTypeMap;
    }

    public constructor() {
    }
}

