/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NullOrder } from '../models/NullOrder';
import { SortDirection } from '../models/SortDirection';
import { HttpFile } from '../http/http';

export class SortField {
    'sourceId': number;
    'transform': string;
    'direction': SortDirection;
    'nullOrder': NullOrder;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sourceId",
            "baseName": "source-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "transform",
            "baseName": "transform",
            "type": "string",
            "format": ""
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "SortDirection",
            "format": ""
        },
        {
            "name": "nullOrder",
            "baseName": "null-order",
            "type": "NullOrder",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SortField.attributeTypeMap;
    }

    public constructor() {
    }
}

