/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataLogInner } from '../models/MetadataLogInner';
import { PartitionSpec } from '../models/PartitionSpec';
import { Schema } from '../models/Schema';
import { Snapshot } from '../models/Snapshot';
import { SnapshotLogInner } from '../models/SnapshotLogInner';
import { SnapshotReference } from '../models/SnapshotReference';
import { SortOrder } from '../models/SortOrder';
import { HttpFile } from '../http/http';

export class TableMetadata {
    'formatVersion': number;
    'tableUuid': string;
    'location'?: string;
    'lastUpdatedMs'?: number;
    'properties'?: { [key: string]: string; };
    'schemas'?: Array<Schema>;
    'currentSchemaId'?: number;
    'lastColumnId'?: number;
    'partitionSpecs'?: Array<PartitionSpec>;
    'defaultSpecId'?: number;
    'lastPartitionId'?: number;
    'sortOrders'?: Array<SortOrder>;
    'defaultSortOrderId'?: number;
    'snapshots'?: Array<Snapshot>;
    'refs'?: { [key: string]: SnapshotReference; };
    'currentSnapshotId'?: number;
    'snapshotLog'?: Array<SnapshotLogInner>;
    'metadataLog'?: Array<MetadataLogInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "formatVersion",
            "baseName": "format-version",
            "type": "number",
            "format": ""
        },
        {
            "name": "tableUuid",
            "baseName": "table-uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastUpdatedMs",
            "baseName": "last-updated-ms",
            "type": "number",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "schemas",
            "baseName": "schemas",
            "type": "Array<Schema>",
            "format": ""
        },
        {
            "name": "currentSchemaId",
            "baseName": "current-schema-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastColumnId",
            "baseName": "last-column-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "partitionSpecs",
            "baseName": "partition-specs",
            "type": "Array<PartitionSpec>",
            "format": ""
        },
        {
            "name": "defaultSpecId",
            "baseName": "default-spec-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastPartitionId",
            "baseName": "last-partition-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "sortOrders",
            "baseName": "sort-orders",
            "type": "Array<SortOrder>",
            "format": ""
        },
        {
            "name": "defaultSortOrderId",
            "baseName": "default-sort-order-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "snapshots",
            "baseName": "snapshots",
            "type": "Array<Snapshot>",
            "format": ""
        },
        {
            "name": "refs",
            "baseName": "refs",
            "type": "{ [key: string]: SnapshotReference; }",
            "format": ""
        },
        {
            "name": "currentSnapshotId",
            "baseName": "current-snapshot-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "snapshotLog",
            "baseName": "snapshot-log",
            "type": "Array<SnapshotLogInner>",
            "format": ""
        },
        {
            "name": "metadataLog",
            "baseName": "metadata-log",
            "type": "Array<MetadataLogInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TableMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

