/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Assertions from the client that must be valid for the commit to succeed. Assertions are identified by `type` - - `assert-create` - the table must not already exist; used for create transactions - `assert-table-uuid` - the table UUID must match the requirement's `uuid` - `assert-ref-snapshot-id` - the table branch or tag identified by the requirement's `ref` must reference the requirement's `snapshot-id`; if `snapshot-id` is `null` or missing, the ref must not already exist - `assert-last-assigned-field-id` - the table's last assigned column id must match the requirement's `last-assigned-field-id` - `assert-current-schema-id` - the table's current schema id must match the requirement's `current-schema-id` - `assert-last-assigned-partition-id` - the table's last assigned partition id must match the requirement's `last-assigned-partition-id` - `assert-default-spec-id` - the table's default spec id must match the requirement's `default-spec-id` - `assert-default-sort-order-id` - the table's default sort order id must match the requirement's `default-sort-order-id`
*/
export class TableRequirement {
    'requirement': TableRequirementRequirementEnum;
    'ref'?: string;
    'uuid'?: string;
    'snapshotId'?: number;
    'lastAssignedFieldId'?: number;
    'currentSchemaId'?: number;
    'lastAssignedPartitionId'?: number;
    'defaultSpecId'?: number;
    'defaultSortOrderId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requirement",
            "baseName": "requirement",
            "type": "TableRequirementRequirementEnum",
            "format": ""
        },
        {
            "name": "ref",
            "baseName": "ref",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "snapshotId",
            "baseName": "snapshot-id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "lastAssignedFieldId",
            "baseName": "last-assigned-field-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "currentSchemaId",
            "baseName": "current-schema-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastAssignedPartitionId",
            "baseName": "last-assigned-partition-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "defaultSpecId",
            "baseName": "default-spec-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "defaultSortOrderId",
            "baseName": "default-sort-order-id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TableRequirement.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TableRequirementRequirementEnum = "assert-create" | "assert-table-uuid" | "assert-ref-snapshot-id" | "assert-last-assigned-field-id" | "assert-current-schema-id" | "assert-last-assigned-partition-id" | "assert-default-spec-id" | "assert-default-sort-order-id" ;

