/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddPartitionSpecUpdate } from '../models/AddPartitionSpecUpdate';
import { AddSchemaUpdate } from '../models/AddSchemaUpdate';
import { AddSnapshotUpdate } from '../models/AddSnapshotUpdate';
import { AddSortOrderUpdate } from '../models/AddSortOrderUpdate';
import { PartitionSpec } from '../models/PartitionSpec';
import { RemovePropertiesUpdate } from '../models/RemovePropertiesUpdate';
import { RemoveSnapshotRefUpdate } from '../models/RemoveSnapshotRefUpdate';
import { RemoveSnapshotsUpdate } from '../models/RemoveSnapshotsUpdate';
import { Schema } from '../models/Schema';
import { SetCurrentSchemaUpdate } from '../models/SetCurrentSchemaUpdate';
import { SetDefaultSortOrderUpdate } from '../models/SetDefaultSortOrderUpdate';
import { SetDefaultSpecUpdate } from '../models/SetDefaultSpecUpdate';
import { SetLocationUpdate } from '../models/SetLocationUpdate';
import { SetPropertiesUpdate } from '../models/SetPropertiesUpdate';
import { SetSnapshotRefUpdate } from '../models/SetSnapshotRefUpdate';
import { Snapshot } from '../models/Snapshot';
import { SortOrder } from '../models/SortOrder';
import { UpgradeFormatVersionUpdate } from '../models/UpgradeFormatVersionUpdate';
import { HttpFile } from '../http/http';

export class TableUpdate {
    'action': TableUpdateActionEnum;
    'formatVersion': number;
    'schema': Schema;
    /**
    * Schema ID to set as current, or -1 to set last added schema
    */
    'schemaId': number;
    'spec': PartitionSpec;
    /**
    * Partition spec ID to set as the default, or -1 to set last added spec
    */
    'specId': number;
    'sortOrder': SortOrder;
    /**
    * Sort order ID to set as the default, or -1 to set last added sort order
    */
    'sortOrderId': number;
    'snapshot': Snapshot;
    'type': TableUpdateTypeEnum;
    'snapshotId': number;
    'maxRefAgeMs'?: number;
    'maxSnapshotAgeMs'?: number;
    'minSnapshotsToKeep'?: number;
    'refName': string;
    'snapshotIds': Array<number>;
    'location': string;
    'updates': { [key: string]: string; };
    'removals': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "TableUpdateActionEnum",
            "format": ""
        },
        {
            "name": "formatVersion",
            "baseName": "format-version",
            "type": "number",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "Schema",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "spec",
            "baseName": "spec",
            "type": "PartitionSpec",
            "format": ""
        },
        {
            "name": "specId",
            "baseName": "spec-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "sortOrder",
            "baseName": "sort-order",
            "type": "SortOrder",
            "format": ""
        },
        {
            "name": "sortOrderId",
            "baseName": "sort-order-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "snapshot",
            "baseName": "snapshot",
            "type": "Snapshot",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TableUpdateTypeEnum",
            "format": ""
        },
        {
            "name": "snapshotId",
            "baseName": "snapshot-id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxRefAgeMs",
            "baseName": "max-ref-age-ms",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxSnapshotAgeMs",
            "baseName": "max-snapshot-age-ms",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minSnapshotsToKeep",
            "baseName": "min-snapshots-to-keep",
            "type": "number",
            "format": ""
        },
        {
            "name": "refName",
            "baseName": "ref-name",
            "type": "string",
            "format": ""
        },
        {
            "name": "snapshotIds",
            "baseName": "snapshot-ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "updates",
            "baseName": "updates",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "removals",
            "baseName": "removals",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TableUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TableUpdateActionEnum = "upgrade-format-version" | "add-schema" | "set-current-schema" | "add-spec" | "set-default-spec" | "add-sort-order" | "set-default-sort-order" | "add-snapshot" | "set-snapshot-ref" | "remove-snapshots" | "remove-snapshot-ref" | "set-location" | "set-properties" | "remove-properties" ;
export type TableUpdateTypeEnum = "tag" | "branch" ;

