/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransformTerm } from '../models/TransformTerm';
import { HttpFile } from '../http/http';

export class Term {
    'type': TermTypeEnum;
    'transform': string;
    'term': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TermTypeEnum",
            "format": ""
        },
        {
            "name": "transform",
            "baseName": "transform",
            "type": "string",
            "format": ""
        },
        {
            "name": "term",
            "baseName": "term",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Term.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TermTypeEnum = "transform" ;

