/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListType } from '../models/ListType';
import { MapType } from '../models/MapType';
import { StructField } from '../models/StructField';
import { StructType } from '../models/StructType';
import { HttpFile } from '../http/http';

export class Type {
    'type': TypeTypeEnum;
    'fields': Array<StructField>;
    'elementId': number;
    'element': Type;
    'elementRequired': boolean;
    'keyId': number;
    'key': Type;
    'valueId': number;
    'value': Type;
    'valueRequired': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TypeTypeEnum",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<StructField>",
            "format": ""
        },
        {
            "name": "elementId",
            "baseName": "element-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "element",
            "baseName": "element",
            "type": "Type",
            "format": ""
        },
        {
            "name": "elementRequired",
            "baseName": "element-required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "keyId",
            "baseName": "key-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "Type",
            "format": ""
        },
        {
            "name": "valueId",
            "baseName": "value-id",
            "type": "number",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Type",
            "format": ""
        },
        {
            "name": "valueRequired",
            "baseName": "value-required",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Type.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TypeTypeEnum = "map" ;

