/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateProperties200Response {
    /**
    * List of property keys that were added or updated
    */
    'updated': Set<string>;
    /**
    * List of properties that were removed
    */
    'removed': Array<string>;
    /**
    * List of properties requested for removal that were not found in the namespace's properties. Represents a partial success response. Server's do not need to implement this.
    */
    'missing'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "missing",
            "baseName": "missing",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateProperties200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

